#!/usr/bin/env python

import sys
import urllib.parse
import subprocess
import spacy
if not sys.argv:
    sys.exit()

nlp = spacy.load('en_core_web_sm', exclude=['parser', 'ner'])
doc = nlp(sys.argv[1])
subprocess.Popen([
    'open',
    'dict://' +
    urllib.parse.quote_plus([token.lemma_ for token in doc][0])
])